### ISSUE TITLE
adb shell "getprop|grep -iE 'build.type|root.support'" leads to: the system cannot find the path specified

### ISSUE THREAD

**Issue by zhangxaochen** [horeah/PyCmd#14]
Dear sir,
When I try "PyCmd 20230424-x64", running `adb shell "getprop|grep -iE 'build.type|root.support'"` leads to `the system cannot find the path specified`, is it a bug?
"PyCmd 20210310-x64" handle this cmd correctly

**Comment by horeah** [comment]
This problem has been introduced when PyCmd switched to using delayed expansion (/V:ON) by default. 
Running PyCmd.exe /V:OFF makes it work, but of course disables some valuable functionality such as showing the ERRORLEVEL in the prompt.

I will look into this -- thanks for reporting!

**Comment by horeah** [comment]
@zhangxaochen Does escaping the second | via caret (^) make it work? I.e.

`adb shell "getprop|grep -iE 'build.type^|root.support'"`

**Comment by horeah** [comment]
This has been fixed in release 20240904.
